# Generated by Django 5.1.8 on 2025-04-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
